---
- name: Installation d'un service redis sur les cibles Debian
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Installation de redis
      ansible.builtin.package:
        update_cache: true
        name: "{{ redis_package_name }}"
        state: present
