---
- name: Clauses when
  hosts: all

  tasks:
    - name: Tâche limitée à la distribution Debian
      ansible.builtin.debug:
        msg: "Distribution ({{ ansible_distribution }}) supportée"
      when:
        - ansible_distribution | lower in ('debian','ubuntu')
        - ansible_architecture == 'x86_64'

    - name: Bloc when
      block:
      - name: Tâche test I
        ansible.builtin.debug:
          msg: "Test I"

      - name: Tâche test II
        ansible.builtin.debug:
          msg: "Test II"
      when: ansible_distribution_version | int == 11
