---
- name: Installation d'un service redis sur les cibles Debian
  hosts: all
  become: true

  tasks:
    - name: Installation de redis
      ansible.builtin.package:
        update_cache: true
        name: "{{ redis_package_name }}"
        state: present

    - name: Rendre le service accessible depuis l'extérieur
      ansible.builtin.lineinfile:
        regex: ^bind 127.0.0.1
        line: "bind {{ ip_addr }}"
        path: /etc/redis/redis.conf
        backup: true
      when:
        - inventory_hostname == 'debiancli'
        - ip_addr | regex_search('^192.168') != none
      loop: "{{ ansible_all_ipv4_addresses }}"
      loop_control:
        loop_var: ip_addr
      notify: restart_redis


  handlers:
    - name: Redémarrage du service redis
      ansible.builtin.systemd_service:
        name: redis-server.service
        state: restarted
      listen: restart_redis
