---
- name: Mise en situation n°1
  hosts: all
  become: true

  pre_tasks:
    - name: IP de fedoracli
      ansible.builtin.set_fact:
        php_srv_addr: "{{ hostvars.fedoracli.ansible_enp0s8.ipv4.address }}"
      when:
        - inventory_hostname == "debiancli"

  roles:
    - role: nginx
      php_server_addr: "{{ php_srv_addr }}"
      when: inventory_hostname == 'debiancli'
    - role: php-fpm
      when: inventory_hostname == 'fedoracli'
    - role: geerlingguy.mysql
      mysql_databases:
        - name: stage
      mysql_users:
        - name: bob
          password: azerty
          priv: "stage.*:ALL"
      when: inventory_hostname == "debiancli"
      tags: install_mariadb

  post_tasks:
    - name: Copie des fichiers de site
      ansible.builtin.copy:
        src: site/
        dest: "{{ document_root }}"
