---
- name: Illustration de la clause loop
  hosts: debiancli

  vars:
    couleurs:
      - fr: vert
        en: green
      - fr: marron
        en: brown

  tasks:
    - name: Boucle simple
      ansible.builtin.debug:
        msg: "Valeur n°{{ idx+1 }}: {{ data }}"
      loop:
        - valeur_1
        - valeur_2
        - valeur_3
      loop_control:
        loop_var: data
        index_var: idx

    - name: Boucle sur une variable liste
      ansible.builtin.debug:
        msg: "IP n°{{ idx+1 }}: {{ ip_addr }}"
      loop: "{{ ansible_all_ipv4_addresses }}"
      loop_control:
        loop_var: ip_addr
        index_var: idx
      when: ip_addr | regex_search('^192') != none


    - name: Boucle sur une liste de dictionnaires
      ansible.builtin.debug:
        msg: "{{ item.fr }} -> {{ item.en }}"
      loop: "{{ couleurs }}"
