---
- name: Mise en situation n°1
  hosts: all
  become: true

  roles:
    - role: nginx
      when: inventory_hostname == 'debiancli'
    - role: php-fpm
      when: inventory_hostname == 'fedoracli'

  post_tasks:
    - name: Copie des fichiers de site
      ansible.builtin.copy:
        src: site/
        dest: "{{ document_root }}"
