        - name: Installation
          ansible.builtin.package:
            name: nginx
            state: present

        - name: Copie du fichier de configuration
          ansible.builtin.template:
            src: nginx/default
            dest: /etc/nginx/sites-available 
          notify: restart_nginx

        - name: Configuration du service
          ansible.builtin.systemd:
            name: nginx
            enabled: true
            state: started

